modLoader="javafml" #mandatory
loaderVersion="[37,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
issueTrackerURL="" #optional
license="MIT"

[[mods]] #mandatory
    modId="mobuildingblocks"
    version="1.2.2"
    displayName="Mo' Building Blocks"
    updateJSONURL=""
    displayURL=""
    logoFile=""
    credits=""
    authors="Team Arcanum"
    description='''
    '''

[[dependencies.mobuildingblocks]]
    modId="forge"
    mandatory=true
    versionRange="[37,)"
    side="BOTH"

[[dependencies.mobuildingblocks]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1]"
    side="BOTH"